// Code generated by qtc from "domain.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line domain.qtpl:1
package cdprototpl

//line domain.qtpl:1
import (
	"github.com/chromedp/pdlgen/util/pdl"
)

// DomainTemplate is the template for a single domain.

//line domain.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line domain.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line domain.qtpl:6
func StreamDomainTemplate(qw422016 *qt422016.Writer, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:6
	qw422016.N().S(`
`)
//line domain.qtpl:7
	for _, c := range d.Commands {
//line domain.qtpl:7
		qw422016.N().S(`
`)
//line domain.qtpl:8
		qw422016.N().S(CommandTemplate(c, d, domains))
//line domain.qtpl:8
		qw422016.N().S(`
`)
//line domain.qtpl:9
	}
//line domain.qtpl:9
	qw422016.N().S(`
`)
//line domain.qtpl:10
	if len(d.Commands) > 0 {
//line domain.qtpl:10
		qw422016.N().S(`
// Command names.
const (
`)
//line domain.qtpl:13
		for _, c := range d.Commands {
//line domain.qtpl:13
			qw422016.N().S(`
	`)
//line domain.qtpl:14
			qw422016.N().S(CommandMethodType(c, nil))
//line domain.qtpl:14
			qw422016.N().S(` = `)
//line domain.qtpl:14
			qw422016.N().Q(ProtoName(c, d))
//line domain.qtpl:14
		}
//line domain.qtpl:14
		qw422016.N().S(`)
`)
//line domain.qtpl:15
	}
//line domain.qtpl:15
	qw422016.N().S(`
`)
//line domain.qtpl:16
}

//line domain.qtpl:16
func WriteDomainTemplate(qq422016 qtio422016.Writer, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line domain.qtpl:16
	StreamDomainTemplate(qw422016, d, domains)
//line domain.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line domain.qtpl:16
}

//line domain.qtpl:16
func DomainTemplate(d *pdl.Domain, domains []*pdl.Domain) string {
//line domain.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line domain.qtpl:16
	WriteDomainTemplate(qb422016, d, domains)
//line domain.qtpl:16
	qs422016 := string(qb422016.B)
//line domain.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line domain.qtpl:16
	return qs422016
//line domain.qtpl:16
}

// CommandTemplate is the general command template.

//line domain.qtpl:19
func StreamCommandTemplate(qw422016 *qt422016.Writer, c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:19
	qw422016.N().S(`
`)
//line domain.qtpl:20
	/* add *Param type */

//line domain.qtpl:20
	qw422016.N().S(`
`)
//line domain.qtpl:21
	qw422016.N().S(TypeTemplate(c, CommandTypePrefix, CommandTypeSuffix, d, domains, nil, false, true))
//line domain.qtpl:21
	qw422016.N().S(`

`)
//line domain.qtpl:23
	/* add Command func */

//line domain.qtpl:23
	qw422016.N().S(`
`)
//line domain.qtpl:24
	qw422016.N().S(CommandFuncTemplate(c, d, domains))
//line domain.qtpl:24
	qw422016.N().S(`

`)
//line domain.qtpl:26
	/* add param funcs (only if it has parameters and a returns). */

//line domain.qtpl:26
	qw422016.N().S(`
`)
//line domain.qtpl:27
	if len(c.Parameters) != 0 {
//line domain.qtpl:27
		for _, p := range c.Parameters {
//line domain.qtpl:27
			if !p.Optional {
//line domain.qtpl:27
				continue
//line domain.qtpl:27
			}
//line domain.qtpl:27
			qw422016.N().S(`
`)
//line domain.qtpl:28
			qw422016.N().S(CommandOptionFuncTemplate(p, c, d, domains))
//line domain.qtpl:28
			qw422016.N().S(`
`)
//line domain.qtpl:29
		}
//line domain.qtpl:29
	}
//line domain.qtpl:29
	qw422016.N().S(`

`)
//line domain.qtpl:31
	/* add *Returns type */

//line domain.qtpl:31
	qw422016.N().S(`
`)
//line domain.qtpl:32
	if len(c.Returns) != 0 {
//line domain.qtpl:32
		qw422016.N().S(`
`)
//line domain.qtpl:33
		qw422016.N().S(TypeTemplate(&pdl.Type{
			RawType:     "returns",
			RawName:     c.RawName,
			Name:        c.Name,
			Type:        pdl.TypeObject,
			Description: "Return values.",
			Properties:  c.Returns,
		}, CommandReturnsPrefix, CommandReturnsSuffix, d, domains, nil, false, false))
//line domain.qtpl:40
		qw422016.N().S(`
`)
//line domain.qtpl:41
	}
//line domain.qtpl:41
	qw422016.N().S(`

`)
//line domain.qtpl:43
	/* add CommandParams.Do func */

//line domain.qtpl:43
	qw422016.N().S(`
`)
//line domain.qtpl:44
	qw422016.N().S(CommandDoFuncTemplate(c, d, domains))
//line domain.qtpl:44
	qw422016.N().S(`
`)
//line domain.qtpl:45
}

//line domain.qtpl:45
func WriteCommandTemplate(qq422016 qtio422016.Writer, c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line domain.qtpl:45
	StreamCommandTemplate(qw422016, c, d, domains)
//line domain.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line domain.qtpl:45
}

//line domain.qtpl:45
func CommandTemplate(c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) string {
//line domain.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line domain.qtpl:45
	WriteCommandTemplate(qb422016, c, d, domains)
//line domain.qtpl:45
	qs422016 := string(qb422016.B)
//line domain.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line domain.qtpl:45
	return qs422016
//line domain.qtpl:45
}

// CommandFuncTemplate is the command func template.

//line domain.qtpl:48
func StreamCommandFuncTemplate(qw422016 *qt422016.Writer, c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:49
	cmdName := CamelName(c)
	typ := CommandType(c)

//line domain.qtpl:51
	qw422016.N().S(`
`)
//line domain.qtpl:52
	qw422016.N().S(FormatComment(c.Description, "", cmdName+" "))
//line domain.qtpl:52
	qw422016.N().S(`
//
// See: `)
//line domain.qtpl:54
	qw422016.N().S(DocRefLink(c))
//line domain.qtpl:54
	if len(c.Parameters) > 0 {
//line domain.qtpl:54
		qw422016.N().S(`
//
// parameters:`)
//line domain.qtpl:56
		for _, p := range c.Parameters {
//line domain.qtpl:56
			if p.Optional {
//line domain.qtpl:56
				continue
//line domain.qtpl:56
			}
//line domain.qtpl:56
			qw422016.N().S(`
//   `)
//line domain.qtpl:57
			qw422016.N().S(ParamDesc(p))
//line domain.qtpl:57
			if p.Optional {
//line domain.qtpl:57
				qw422016.N().S(` (optional)`)
//line domain.qtpl:57
			}
//line domain.qtpl:57
		}
//line domain.qtpl:57
	}
//line domain.qtpl:57
	qw422016.N().S(`
func `)
//line domain.qtpl:58
	qw422016.N().S(cmdName)
//line domain.qtpl:58
	qw422016.N().S(`(`)
//line domain.qtpl:58
	qw422016.N().S(ParamList(c, d, domains, false))
//line domain.qtpl:58
	qw422016.N().S(`) *`)
//line domain.qtpl:58
	qw422016.N().S(typ)
//line domain.qtpl:58
	qw422016.N().S(`{
	return &`)
//line domain.qtpl:59
	qw422016.N().S(typ)
//line domain.qtpl:59
	qw422016.N().S(`{`)
//line domain.qtpl:59
	for _, t := range c.Parameters {
//line domain.qtpl:59
		if !t.Optional {
//line domain.qtpl:59
			qw422016.N().S(`
		`)
//line domain.qtpl:60
			qw422016.N().S(GoName(t, false))
//line domain.qtpl:60
			qw422016.N().S(`: `)
//line domain.qtpl:60
			qw422016.N().S(GoName(t, true))
//line domain.qtpl:60
			qw422016.N().S(`,`)
//line domain.qtpl:60
		}
//line domain.qtpl:60
	}
//line domain.qtpl:60
	qw422016.N().S(`
	}
}
`)
//line domain.qtpl:63
}

//line domain.qtpl:63
func WriteCommandFuncTemplate(qq422016 qtio422016.Writer, c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line domain.qtpl:63
	StreamCommandFuncTemplate(qw422016, c, d, domains)
//line domain.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line domain.qtpl:63
}

//line domain.qtpl:63
func CommandFuncTemplate(c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) string {
//line domain.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line domain.qtpl:63
	WriteCommandFuncTemplate(qb422016, c, d, domains)
//line domain.qtpl:63
	qs422016 := string(qb422016.B)
//line domain.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line domain.qtpl:63
	return qs422016
//line domain.qtpl:63
}

// CommandOptionFuncTemplate is the command option func template.

//line domain.qtpl:66
func StreamCommandOptionFuncTemplate(qw422016 *qt422016.Writer, t *pdl.Type, c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:67
	n := GoName(t, false)
	optName := OptionFuncPrefix + n + OptionFuncSuffix
	typ := CommandType(c)
	v := GoName(t, true)

//line domain.qtpl:71
	qw422016.N().S(`
`)
//line domain.qtpl:72
	qw422016.N().S(FormatComment(t.Description, "", optName+" "))
//line domain.qtpl:72
	qw422016.N().S(`
func (p `)
//line domain.qtpl:73
	qw422016.N().S(typ)
//line domain.qtpl:73
	qw422016.N().S(`) `)
//line domain.qtpl:73
	qw422016.N().S(optName)
//line domain.qtpl:73
	qw422016.N().S(`(`)
//line domain.qtpl:73
	qw422016.N().S(v)
//line domain.qtpl:73
	qw422016.N().S(` `)
//line domain.qtpl:73
	qw422016.N().S(GoType(t, d, domains))
//line domain.qtpl:73
	qw422016.N().S(`) *`)
//line domain.qtpl:73
	qw422016.N().S(typ)
//line domain.qtpl:73
	qw422016.N().S(`{
	p.`)
//line domain.qtpl:74
	qw422016.N().S(n)
//line domain.qtpl:74
	qw422016.N().S(` = `)
//line domain.qtpl:74
	qw422016.N().S(v)
//line domain.qtpl:74
	qw422016.N().S(`
	return &p
}
`)
//line domain.qtpl:77
}

//line domain.qtpl:77
func WriteCommandOptionFuncTemplate(qq422016 qtio422016.Writer, t *pdl.Type, c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:77
	qw422016 := qt422016.AcquireWriter(qq422016)
//line domain.qtpl:77
	StreamCommandOptionFuncTemplate(qw422016, t, c, d, domains)
//line domain.qtpl:77
	qt422016.ReleaseWriter(qw422016)
//line domain.qtpl:77
}

//line domain.qtpl:77
func CommandOptionFuncTemplate(t *pdl.Type, c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) string {
//line domain.qtpl:77
	qb422016 := qt422016.AcquireByteBuffer()
//line domain.qtpl:77
	WriteCommandOptionFuncTemplate(qb422016, t, c, d, domains)
//line domain.qtpl:77
	qs422016 := string(qb422016.B)
//line domain.qtpl:77
	qt422016.ReleaseByteBuffer(qb422016)
//line domain.qtpl:77
	return qs422016
//line domain.qtpl:77
}

// CommandDoFuncTemplate is the command do func template.

//line domain.qtpl:80
func StreamCommandDoFuncTemplate(qw422016 *qt422016.Writer, c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:81
	typ := CommandType(c)

	hasEmptyParams := len(c.Parameters) == 0
	hasEmptyRet := len(c.Returns) == 0

	emptyRet := EmptyRetList(c, d, domains)
	if emptyRet != "" {
		emptyRet += ", "
	}

	retTypeList := RetTypeList(c, d, domains)
	if retTypeList != "" {
		retTypeList += ", "
	}

	retValueList := RetNameList(c, "res", d, domains)
	if retValueList != "" {
		retValueList += ", "
	}

	b64ret := Base64EncodedRetParam(c)

	// determine if there's a conditional that indicates whether or not the
	// returned value is b64 encoded.
	var b64cond bool
	for _, p := range c.Returns {
		if p.Name == Base64EncodedParamName {
			b64cond = true
			break
		}
	}

	pval := "p"
	if hasEmptyParams {
		pval = "nil"
	}

//line domain.qtpl:117
	qw422016.N().S(`
// Do executes `)
//line domain.qtpl:118
	qw422016.N().S(c.RawName)
//line domain.qtpl:118
	qw422016.N().S(` against the provided context.`)
//line domain.qtpl:118
	if !hasEmptyRet {
//line domain.qtpl:118
		qw422016.N().S(`
//
// returns:`)
//line domain.qtpl:120
		for _, p := range c.Returns {
//line domain.qtpl:120
			if p.Name == Base64EncodedParamName {
//line domain.qtpl:120
				continue
//line domain.qtpl:120
			}
//line domain.qtpl:120
			qw422016.N().S(`
//   `)
//line domain.qtpl:121
			qw422016.N().S(ParamDesc(p))
//line domain.qtpl:121
		}
//line domain.qtpl:121
	}
//line domain.qtpl:121
	qw422016.N().S(`
func (p *`)
//line domain.qtpl:122
	qw422016.N().S(typ)
//line domain.qtpl:122
	qw422016.N().S(`) Do(ctx context.Context) (`)
//line domain.qtpl:122
	qw422016.N().S(retTypeList)
//line domain.qtpl:122
	qw422016.N().S(`err error) {`)
//line domain.qtpl:122
	if hasEmptyRet {
//line domain.qtpl:122
		qw422016.N().S(`
	return cdp.Execute(ctx, `)
//line domain.qtpl:123
		qw422016.N().S(CommandMethodType(c, nil))
//line domain.qtpl:123
		qw422016.N().S(`, `)
//line domain.qtpl:123
		qw422016.N().S(pval)
//line domain.qtpl:123
		qw422016.N().S(`, nil)`)
//line domain.qtpl:123
	} else {
//line domain.qtpl:123
		qw422016.N().S(`
	// execute
	var res `)
//line domain.qtpl:125
		qw422016.N().S(CommandReturnsType(c))
//line domain.qtpl:125
		qw422016.N().S(`
	err = cdp.Execute(ctx, `)
//line domain.qtpl:126
		qw422016.N().S(CommandMethodType(c, nil))
//line domain.qtpl:126
		qw422016.N().S(`, `)
//line domain.qtpl:126
		qw422016.N().S(pval)
//line domain.qtpl:126
		qw422016.N().S(`, &res)
	if err != nil {
		return `)
//line domain.qtpl:128
		qw422016.N().S(emptyRet)
//line domain.qtpl:128
		qw422016.N().S(`err
	}
	`)
//line domain.qtpl:130
		if b64ret != nil {
//line domain.qtpl:130
			qw422016.N().S(`
	// decode
	var dec []byte`)
//line domain.qtpl:132
			if b64cond {
//line domain.qtpl:132
				qw422016.N().S(`
	if res.Base64encoded {`)
//line domain.qtpl:133
			}
//line domain.qtpl:133
			qw422016.N().S(`
		dec, err = base64.StdEncoding.DecodeString(res.`)
//line domain.qtpl:134
			qw422016.N().S(GoName(b64ret, false))
//line domain.qtpl:134
			qw422016.N().S(`)
		if err != nil {
			return `)
//line domain.qtpl:136
			qw422016.N().S(emptyRet)
//line domain.qtpl:136
			qw422016.N().S(`err
		}`)
//line domain.qtpl:137
			if b64cond {
//line domain.qtpl:137
				qw422016.N().S(`
	} else {
		dec = []byte(res.`)
//line domain.qtpl:139
				qw422016.N().S(GoName(b64ret, false))
//line domain.qtpl:139
				qw422016.N().S(`)
	}`)
//line domain.qtpl:140
			}
//line domain.qtpl:140
		}
//line domain.qtpl:140
		qw422016.N().S(`
	return `)
//line domain.qtpl:141
		qw422016.N().S(retValueList)
//line domain.qtpl:141
		qw422016.N().S(`nil`)
//line domain.qtpl:141
	}
//line domain.qtpl:141
	qw422016.N().S(`
}
`)
//line domain.qtpl:143
}

//line domain.qtpl:143
func WriteCommandDoFuncTemplate(qq422016 qtio422016.Writer, c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) {
//line domain.qtpl:143
	qw422016 := qt422016.AcquireWriter(qq422016)
//line domain.qtpl:143
	StreamCommandDoFuncTemplate(qw422016, c, d, domains)
//line domain.qtpl:143
	qt422016.ReleaseWriter(qw422016)
//line domain.qtpl:143
}

//line domain.qtpl:143
func CommandDoFuncTemplate(c *pdl.Type, d *pdl.Domain, domains []*pdl.Domain) string {
//line domain.qtpl:143
	qb422016 := qt422016.AcquireByteBuffer()
//line domain.qtpl:143
	WriteCommandDoFuncTemplate(qb422016, c, d, domains)
//line domain.qtpl:143
	qs422016 := string(qb422016.B)
//line domain.qtpl:143
	qt422016.ReleaseByteBuffer(qb422016)
//line domain.qtpl:143
	return qs422016
//line domain.qtpl:143
}
