// Code generated by qtc from "extra.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line extra.qtpl:1
package cdprototpl

//line extra.qtpl:1
import (
	"github.com/chromedp/pdlgen/util/pdl"
)

// ExtraTimestampTemplate is a special template for the Timestamp type that
// defines its JSON unmarshaling.

//line extra.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line extra.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line extra.qtpl:7
func StreamExtraTimestampTemplate(qw422016 *qt422016.Writer, t *pdl.Type, d *pdl.Domain) {
//line extra.qtpl:8
	typ := t.Name
	monotonic := t.TimestampType == pdl.TimestampTypeMonotonic
	timeRes := "time.Millisecond"
	if t.TimestampType != pdl.TimestampTypeMillisecond {
		timeRes = "time.Second"
	}

//line extra.qtpl:14
	qw422016.N().S(`
`)
//line extra.qtpl:15
	if monotonic {
//line extra.qtpl:15
		qw422016.N().S(`
// `)
//line extra.qtpl:16
		qw422016.N().S(typ)
//line extra.qtpl:16
		qw422016.N().S(`Epoch is the `)
//line extra.qtpl:16
		qw422016.N().S(typ)
//line extra.qtpl:16
		qw422016.N().S(` time epoch.
var `)
//line extra.qtpl:17
		qw422016.N().S(typ)
//line extra.qtpl:17
		qw422016.N().S(`Epoch *time.Time

func init() {
	// initialize epoch
	bt := sysutil.BootTime()
	`)
//line extra.qtpl:22
		qw422016.N().S(typ)
//line extra.qtpl:22
		qw422016.N().S(`Epoch = &bt
}
`)
//line extra.qtpl:24
	}
//line extra.qtpl:24
	qw422016.N().S(`

// MarshalEasyJSON satisfies easyjson.Marshaler.
func (t `)
//line extra.qtpl:27
	qw422016.N().S(typ)
//line extra.qtpl:27
	qw422016.N().S(`) MarshalEasyJSON(out *jwriter.Writer) {
	v := `)
//line extra.qtpl:28
	if monotonic {
//line extra.qtpl:28
		qw422016.N().S(`float64(time.Time(t).Sub(*`)
//line extra.qtpl:28
		qw422016.N().S(typ)
//line extra.qtpl:28
		qw422016.N().S(`Epoch))/float64(time.Second)`)
//line extra.qtpl:28
	} else {
//line extra.qtpl:28
		qw422016.N().S(`float64(time.Time(t).UnixNano()/int64(`)
//line extra.qtpl:28
		qw422016.N().S(timeRes)
//line extra.qtpl:28
		qw422016.N().S(`))`)
//line extra.qtpl:28
	}
//line extra.qtpl:28
	qw422016.N().S(`

	out.Buffer.EnsureSpace(20)
	out.Buffer.Buf = strconv.AppendFloat(out.Buffer.Buf, v, 'f', -1, 64)
}

// MarshalJSON satisfies json.Marshaler.
func (t `)
//line extra.qtpl:35
	qw422016.N().S(typ)
//line extra.qtpl:35
	qw422016.N().S(`) MarshalJSON() ([]byte, error) {
	return easyjson.Marshal(t)
}

// UnmarshalEasyJSON satisfies easyjson.Unmarshaler.
func (t *`)
//line extra.qtpl:40
	qw422016.N().S(typ)
//line extra.qtpl:40
	qw422016.N().S(`) UnmarshalEasyJSON(in *jlexer.Lexer) {`)
//line extra.qtpl:40
	if monotonic {
//line extra.qtpl:40
		qw422016.N().S(`
	*t = `)
//line extra.qtpl:41
		qw422016.N().S(typ)
//line extra.qtpl:41
		qw422016.N().S(`(`)
//line extra.qtpl:41
		qw422016.N().S(typ)
//line extra.qtpl:41
		qw422016.N().S(`Epoch.Add(time.Duration(in.Float64()*float64(time.Second))))`)
//line extra.qtpl:41
	} else {
//line extra.qtpl:41
		qw422016.N().S(`
	*t = `)
//line extra.qtpl:42
		qw422016.N().S(typ)
//line extra.qtpl:42
		qw422016.N().S(`(time.Unix(0, int64(in.Float64()*float64(`)
//line extra.qtpl:42
		qw422016.N().S(timeRes)
//line extra.qtpl:42
		qw422016.N().S(`))))`)
//line extra.qtpl:42
	}
//line extra.qtpl:42
	qw422016.N().S(`
}

// UnmarshalJSON satisfies json.Unmarshaler.
func (t *`)
//line extra.qtpl:46
	qw422016.N().S(typ)
//line extra.qtpl:46
	qw422016.N().S(`) UnmarshalJSON(buf []byte) error {
	return easyjson.Unmarshal(buf, t)
}
`)
//line extra.qtpl:49
}

//line extra.qtpl:49
func WriteExtraTimestampTemplate(qq422016 qtio422016.Writer, t *pdl.Type, d *pdl.Domain) {
//line extra.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line extra.qtpl:49
	StreamExtraTimestampTemplate(qw422016, t, d)
//line extra.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line extra.qtpl:49
}

//line extra.qtpl:49
func ExtraTimestampTemplate(t *pdl.Type, d *pdl.Domain) string {
//line extra.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line extra.qtpl:49
	WriteExtraTimestampTemplate(qb422016, t, d)
//line extra.qtpl:49
	qs422016 := string(qb422016.B)
//line extra.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line extra.qtpl:49
	return qs422016
//line extra.qtpl:49
}

// ExtraFrameTemplate is a special template for the Page.Frame type, adding FrameState.

//line extra.qtpl:52
func StreamExtraFrameTemplate(qw422016 *qt422016.Writer) {
//line extra.qtpl:52
	qw422016.N().S(`
// FrameState is the state of a Frame.
type FrameState uint16

// FrameState enum values.
const (
    FrameDOMContentEventFired FrameState = 1 << (15 - iota)
    FrameLoadEventFired
    FrameAttached
    FrameNavigated
    FrameLoading
    FrameScheduledNavigation
)

// frameStateNames are the names of the frame states.
var frameStateNames = map[FrameState]string{
    FrameDOMContentEventFired: "DOMContentEventFired",
    FrameLoadEventFired:       "LoadEventFired",
    FrameAttached:             "Attached",
    FrameNavigated:            "Navigated",
	FrameLoading:			   "Loading",
    FrameScheduledNavigation:  "ScheduledNavigation",
}

// String satisfies stringer interface.
func (fs FrameState) String() string {
    var s []string
    for k, v := range frameStateNames {
        if fs&k != 0 {
            s = append(s, v)
        }
    }
    return "[" + strings.Join(s, " ") + "]"
}

// EmptyFrameID is the "non-existent" frame id.
const EmptyFrameID = FrameID("")
`)
//line extra.qtpl:89
}

//line extra.qtpl:89
func WriteExtraFrameTemplate(qq422016 qtio422016.Writer) {
//line extra.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
//line extra.qtpl:89
	StreamExtraFrameTemplate(qw422016)
//line extra.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line extra.qtpl:89
}

//line extra.qtpl:89
func ExtraFrameTemplate() string {
//line extra.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
//line extra.qtpl:89
	WriteExtraFrameTemplate(qb422016)
//line extra.qtpl:89
	qs422016 := string(qb422016.B)
//line extra.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
//line extra.qtpl:89
	return qs422016
//line extra.qtpl:89
}

// ExtraNodeTemplate is a special template for the DOM.Node type, adding NodeState.

//line extra.qtpl:92
func StreamExtraNodeTemplate(qw422016 *qt422016.Writer) {
//line extra.qtpl:92
	qw422016.N().S(`
// AttributeValue returns the named attribute for the node.
func (n *Node) AttributeValue(name string) string {
	value, _ := n.Attribute(name)
	return value
}

// Attribute returns the named attribute for the node and if it exists.
func (n *Node) Attribute(name string) (string, bool) {
	n.RLock()
	defer n.RUnlock()

	for i := 0; i < len(n.Attributes); i += 2 {
		if n.Attributes[i] == name {
			return n.Attributes[i+1], true
		}
	}

	return "", false
}

// xpath builds the xpath string.
func (n *Node) xpath(stopAtDocument, stopAtID bool) string {
	n.RLock()
	defer n.RUnlock()

	p, pos, id := "", "", n.AttributeValue("id")
	switch {
	case n.Parent == nil:
		return n.LocalName

	case stopAtDocument && n.NodeType == NodeTypeDocument:
		return ""

	case stopAtID && id != "":
		p = "/"
		pos = `)
//line extra.qtpl:92
	qw422016.N().S("`")
//line extra.qtpl:92
	qw422016.N().S(`[@id='`)
//line extra.qtpl:92
	qw422016.N().S("`")
//line extra.qtpl:92
	qw422016.N().S(`+id+`)
//line extra.qtpl:92
	qw422016.N().S("`")
//line extra.qtpl:92
	qw422016.N().S(`']`)
//line extra.qtpl:92
	qw422016.N().S("`")
//line extra.qtpl:92
	qw422016.N().S(`

	case n.Parent != nil:
		var i int
		var found bool

		n.Parent.RLock()
		for j := 0; j < len(n.Parent.Children); j++ {
			if n.Parent.Children[j].LocalName == n.LocalName {
				i++
			}
			if n.Parent.Children[j].NodeID == n.NodeID {
				found = true
				break
			}
		}
		n.Parent.RUnlock()

		if found {
			pos = "["+strconv.Itoa(i)+"]"
		}

		p = n.Parent.xpath(stopAtDocument, stopAtID)
	}

	localName := n.LocalName
	if n.IsSVG {
		localName = `)
//line extra.qtpl:92
	qw422016.N().S("`")
//line extra.qtpl:92
	qw422016.N().S(`*[local-name()='`)
//line extra.qtpl:92
	qw422016.N().S("`")
//line extra.qtpl:92
	qw422016.N().S(` + localName + `)
//line extra.qtpl:92
	qw422016.N().S("`")
//line extra.qtpl:92
	qw422016.N().S(`']`)
//line extra.qtpl:92
	qw422016.N().S("`")
//line extra.qtpl:92
	qw422016.N().S(`
	}
	return  p + "/" + localName + pos
}

// PartialXPathByID returns the partial XPath for the node, stopping at the
// first parent with an id attribute or at nearest parent document node.
func (n *Node) PartialXPathByID() string {
	return n.xpath(true, true)
}

// PartialXPath returns the partial XPath for the node, stopping at the nearest
// parent document node.
func (n *Node) PartialXPath() string {
	return n.xpath(true, false)
}

// FullXPathByID returns the full XPath for the node, stopping at the top most
// document root or at the closest parent node with an id attribute.
func (n *Node) FullXPathByID() string {
	return n.xpath(false, true)
}

// FullXPath returns the full XPath for the node, stopping only at the top most
// document root.
func (n *Node) FullXPath() string {
	return n.xpath(false, false)
}

// Dump builds a printable string representation of the node and its children.
func (n *Node) Dump(prefix, indent string, nodeIDs bool) string {
	if n == nil {
		return prefix + "<nil>"
	}

	n.RLock()
	defer n.RUnlock()

	s := n.LocalName
	if s == "" {
		s = n.NodeName
	}

	for i := 0; i < len(n.Attributes); i += 2 {
		if strings.ToLower(n.Attributes[i]) == "id" {
			s += "#" + n.Attributes[i+1]
			break
		}
	}

	if n.NodeType != NodeTypeElement && n.NodeType != NodeTypeText {
		s += fmt.Sprintf(" <%s>", n.NodeType)
	}

	if n.NodeType == NodeTypeText {
		v := n.NodeValue
		if len(v) > 15 {
			v = v[:15] + "..."
		}
		s += fmt.Sprintf(" %q", v)
	}

	if n.NodeType == NodeTypeElement && len(n.Attributes) > 0 {
		attrs := ""
		for i := 0; i < len(n.Attributes); i += 2 {
			if strings.ToLower(n.Attributes[i]) == "id" {
				continue
			}
			if attrs != "" {
				attrs += " "
			}
			attrs += fmt.Sprintf("%s=%q", n.Attributes[i], n.Attributes[i+1])
		}
		if attrs != "" {
			s += " [" + attrs + "]"
		}
	}

	if nodeIDs {
		s += fmt.Sprintf(" (%d)", n.NodeID)
	}

	for i := 0; i < len(n.Children); i++ {
		s += "\n" + n.Children[i].Dump(prefix+indent, indent, nodeIDs)
	}

	return prefix + s
}

// NodeState is the state of a DOM node.
type NodeState uint8

// NodeState enum values.
const (
    NodeReady NodeState = 1 << (7 - iota)
	NodeVisible
	NodeHighlighted
)

// nodeStateNames are the names of the node states.
var nodeStateNames = map[NodeState]string{
    NodeReady:		 "Ready",
    NodeVisible:     "Visible",
    NodeHighlighted: "Highlighted",
}

// String satisfies stringer interface.
func (ns NodeState) String() string {
    var s []string
    for k, v := range nodeStateNames {
        if ns&k != 0 {
            s = append(s, v)
        }
    }
    return "[" + strings.Join(s, " ") + "]"
}

// EmptyNodeID is the "non-existent" node id.
const EmptyNodeID = NodeID(0)
`)
//line extra.qtpl:274
}

//line extra.qtpl:274
func WriteExtraNodeTemplate(qq422016 qtio422016.Writer) {
//line extra.qtpl:274
	qw422016 := qt422016.AcquireWriter(qq422016)
//line extra.qtpl:274
	StreamExtraNodeTemplate(qw422016)
//line extra.qtpl:274
	qt422016.ReleaseWriter(qw422016)
//line extra.qtpl:274
}

//line extra.qtpl:274
func ExtraNodeTemplate() string {
//line extra.qtpl:274
	qb422016 := qt422016.AcquireByteBuffer()
//line extra.qtpl:274
	WriteExtraNodeTemplate(qb422016)
//line extra.qtpl:274
	qs422016 := string(qb422016.B)
//line extra.qtpl:274
	qt422016.ReleaseByteBuffer(qb422016)
//line extra.qtpl:274
	return qs422016
//line extra.qtpl:274
}

// ExtraFixStringUnmarshaler is a template that forces values to be parsed properly.

//line extra.qtpl:277
func StreamExtraFixStringUnmarshaler(qw422016 *qt422016.Writer, typ, parseFunc, extra string) {
//line extra.qtpl:277
	qw422016.N().S(`
// UnmarshalEasyJSON satisfies easyjson.Unmarshaler.
func (t *`)
//line extra.qtpl:279
	qw422016.N().S(typ)
//line extra.qtpl:279
	qw422016.N().S(`) UnmarshalEasyJSON(in *jlexer.Lexer) {
	buf := in.Raw()
	if l := len(buf); l > 2 && buf[0] == '"' && buf[l-1] == '"' {
		buf = buf[1:l-1]
	}
`)
//line extra.qtpl:284
	if parseFunc != "" {
//line extra.qtpl:284
		qw422016.N().S(`
	v, err := strconv.`)
//line extra.qtpl:285
		qw422016.N().S(parseFunc)
//line extra.qtpl:285
		qw422016.N().S(`(string(buf)`)
//line extra.qtpl:285
		qw422016.N().S(extra)
//line extra.qtpl:285
		qw422016.N().S(`)
	if err != nil {
		in.AddError(err)
	}
`)
//line extra.qtpl:289
	}
//line extra.qtpl:289
	qw422016.N().S(`
	*t = `)
//line extra.qtpl:290
	qw422016.N().S(typ)
//line extra.qtpl:290
	qw422016.N().S(`(`)
//line extra.qtpl:290
	if parseFunc != "" {
//line extra.qtpl:290
		qw422016.N().S(`v`)
//line extra.qtpl:290
	} else {
//line extra.qtpl:290
		qw422016.N().S(`buf`)
//line extra.qtpl:290
	}
//line extra.qtpl:290
	qw422016.N().S(`)
}

// UnmarshalJSON satisfies json.Unmarshaler.
func (t *`)
//line extra.qtpl:294
	qw422016.N().S(typ)
//line extra.qtpl:294
	qw422016.N().S(`) UnmarshalJSON(buf []byte) error {
	return easyjson.Unmarshal(buf, t)
}
`)
//line extra.qtpl:297
}

//line extra.qtpl:297
func WriteExtraFixStringUnmarshaler(qq422016 qtio422016.Writer, typ, parseFunc, extra string) {
//line extra.qtpl:297
	qw422016 := qt422016.AcquireWriter(qq422016)
//line extra.qtpl:297
	StreamExtraFixStringUnmarshaler(qw422016, typ, parseFunc, extra)
//line extra.qtpl:297
	qt422016.ReleaseWriter(qw422016)
//line extra.qtpl:297
}

//line extra.qtpl:297
func ExtraFixStringUnmarshaler(typ, parseFunc, extra string) string {
//line extra.qtpl:297
	qb422016 := qt422016.AcquireByteBuffer()
//line extra.qtpl:297
	WriteExtraFixStringUnmarshaler(qb422016, typ, parseFunc, extra)
//line extra.qtpl:297
	qs422016 := string(qb422016.B)
//line extra.qtpl:297
	qt422016.ReleaseByteBuffer(qb422016)
//line extra.qtpl:297
	return qs422016
//line extra.qtpl:297
}

// ExtraExecutorTemplate is the additional shared executor interface for all
// the domains.

//line extra.qtpl:301
func StreamExtraExecutorTemplate(qw422016 *qt422016.Writer) {
//line extra.qtpl:301
	qw422016.N().S(`
// Executor is the common interface for executing a command.
type Executor interface {
	// Execute executes the command.
	Execute(context.Context, string, easyjson.Marshaler, easyjson.Unmarshaler) error
}

// contextKey is the context key type.
type contextKey int

// context keys.
const (
	executorKey contextKey = iota
)

// WithExecutor sets the message executor for the context.
func WithExecutor(parent context.Context, executor Executor) context.Context {
	return context.WithValue(parent, executorKey, executor)
}

// ExecutorFromContext returns the message executor for the context.
func ExecutorFromContext(ctx context.Context) Executor {
	return ctx.Value(executorKey).(Executor)
}

// Execute uses the context's message executor to send a command or event
// method marshaling the provided parameters, and unmarshaling to res.
func Execute(ctx context.Context, method string, params easyjson.Marshaler, res easyjson.Unmarshaler) error {
	if executor := ctx.Value(executorKey); executor != nil {
		return executor.(Executor).Execute(ctx, method, params, res)
	}
	return ErrInvalidContext
}

// Error is a error.
type Error string

// Error values.
const (
	// ErrInvalidContext is the invalid context error.
	ErrInvalidContext Error = "invalid context"

	// ErrMsgMissingParamsOrResult is the msg missing params or result error.
	ErrMsgMissingParamsOrResult Error = "msg missing params or result"
)

// Error satisfies the error interface.
func (err Error) Error() string {
	return string(err)
}

// ErrUnknownCommandOrEvent is an unknown command or event error.
type ErrUnknownCommandOrEvent string

// Error satisfies the error interface.
func (err ErrUnknownCommandOrEvent) Error() string {
	return fmt.Sprintf("unknown command or event %q", string(err))
}

`)
//line extra.qtpl:360
}

//line extra.qtpl:360
func WriteExtraExecutorTemplate(qq422016 qtio422016.Writer) {
//line extra.qtpl:360
	qw422016 := qt422016.AcquireWriter(qq422016)
//line extra.qtpl:360
	StreamExtraExecutorTemplate(qw422016)
//line extra.qtpl:360
	qt422016.ReleaseWriter(qw422016)
//line extra.qtpl:360
}

//line extra.qtpl:360
func ExtraExecutorTemplate() string {
//line extra.qtpl:360
	qb422016 := qt422016.AcquireByteBuffer()
//line extra.qtpl:360
	WriteExtraExecutorTemplate(qb422016)
//line extra.qtpl:360
	qs422016 := string(qb422016.B)
//line extra.qtpl:360
	qt422016.ReleaseByteBuffer(qb422016)
//line extra.qtpl:360
	return qs422016
//line extra.qtpl:360
}

// ExtraMethodTypeTemplate generates the additional MethodType funcs and consts.

//line extra.qtpl:363
func StreamExtraMethodTypeTemplate(qw422016 *qt422016.Writer, domains []*pdl.Domain) {
//line extra.qtpl:363
	qw422016.N().S(`
// Domain returns the Chrome DevTools Protocol domain of the event or command.
func (t MethodType) Domain() string {
	return string(t[:strings.IndexByte(string(t), '.')])
}

// MethodType values.
const (`)
//line extra.qtpl:370
	for _, d := range domains {
//line extra.qtpl:370
		for _, c := range d.Commands {
//line extra.qtpl:370
			qw422016.N().S(`
	`)
//line extra.qtpl:371
			qw422016.N().S(CommandMethodType(c, d))
//line extra.qtpl:371
			qw422016.N().S(` = `)
//line extra.qtpl:371
			qw422016.N().S(PackageName(d))
//line extra.qtpl:371
			qw422016.N().S(`.`)
//line extra.qtpl:371
			qw422016.N().S(CommandMethodType(c, nil))
//line extra.qtpl:371
		}
//line extra.qtpl:371
		for _, e := range d.Events {
//line extra.qtpl:371
			qw422016.N().S(`
	`)
//line extra.qtpl:372
			qw422016.N().S(EventMethodType(e, d))
//line extra.qtpl:372
			qw422016.N().S(` = `)
//line extra.qtpl:372
			qw422016.N().Q(ProtoName(e, d))
//line extra.qtpl:372
		}
//line extra.qtpl:372
	}
//line extra.qtpl:372
	qw422016.N().S(`)
`)
//line extra.qtpl:373
}

//line extra.qtpl:373
func WriteExtraMethodTypeTemplate(qq422016 qtio422016.Writer, domains []*pdl.Domain) {
//line extra.qtpl:373
	qw422016 := qt422016.AcquireWriter(qq422016)
//line extra.qtpl:373
	StreamExtraMethodTypeTemplate(qw422016, domains)
//line extra.qtpl:373
	qt422016.ReleaseWriter(qw422016)
//line extra.qtpl:373
}

//line extra.qtpl:373
func ExtraMethodTypeTemplate(domains []*pdl.Domain) string {
//line extra.qtpl:373
	qb422016 := qt422016.AcquireByteBuffer()
//line extra.qtpl:373
	WriteExtraMethodTypeTemplate(qb422016, domains)
//line extra.qtpl:373
	qs422016 := string(qb422016.B)
//line extra.qtpl:373
	qt422016.ReleaseByteBuffer(qb422016)
//line extra.qtpl:373
	return qs422016
//line extra.qtpl:373
}

// ExtraMessageTemplate generates the additional Message funcs.

//line extra.qtpl:376
func StreamExtraMessageTemplate(qw422016 *qt422016.Writer, domains []*pdl.Domain) {
//line extra.qtpl:376
	qw422016.N().S(`
type empty struct{}
var emptyVal = &empty{}

// UnmarshalMessage unmarshals the message result or params.
func UnmarshalMessage(msg *Message) (interface{}, error) {
	var v easyjson.Unmarshaler
	switch msg.Method {`)
//line extra.qtpl:383
	for _, d := range domains {
//line extra.qtpl:383
		for _, c := range d.Commands {
//line extra.qtpl:383
			qw422016.N().S(`
	case `)
//line extra.qtpl:384
			qw422016.N().S(CommandMethodType(c, d))
//line extra.qtpl:384
			qw422016.N().S(`:`)
//line extra.qtpl:384
			if len(c.Returns) == 0 {
//line extra.qtpl:384
				qw422016.N().S(`
		return emptyVal, nil`)
//line extra.qtpl:385
			} else {
//line extra.qtpl:385
				qw422016.N().S(`
		v = new(`)
//line extra.qtpl:386
				qw422016.N().S(PackageName(d))
//line extra.qtpl:386
				qw422016.N().S(`.`)
//line extra.qtpl:386
				qw422016.N().S(CommandReturnsType(c))
//line extra.qtpl:386
				qw422016.N().S(`)`)
//line extra.qtpl:386
			}
//line extra.qtpl:386
			qw422016.N().S(`
	`)
//line extra.qtpl:387
		}
//line extra.qtpl:387
		for _, e := range d.Events {
//line extra.qtpl:387
			qw422016.N().S(`
	case `)
//line extra.qtpl:388
			qw422016.N().S(EventMethodType(e, d))
//line extra.qtpl:388
			qw422016.N().S(`:
		v = new(`)
//line extra.qtpl:389
			qw422016.N().S(PackageName(d))
//line extra.qtpl:389
			qw422016.N().S(`.`)
//line extra.qtpl:389
			qw422016.N().S(EventType(e))
//line extra.qtpl:389
			qw422016.N().S(`)
	`)
//line extra.qtpl:390
		}
//line extra.qtpl:390
	}
//line extra.qtpl:390
	qw422016.N().S(`
	default:
		return nil, cdp.ErrUnknownCommandOrEvent(msg.Method)
	}

	var buf easyjson.RawMessage
	switch {
	case msg.Params != nil:
		buf = msg.Params

	case msg.Result != nil:
		buf = msg.Result

	default:
		return nil, cdp.ErrMsgMissingParamsOrResult
	}

	err := easyjson.Unmarshal(buf, v)
	if err != nil {
		return nil, err
	}

	return v, nil
}
`)
//line extra.qtpl:414
}

//line extra.qtpl:414
func WriteExtraMessageTemplate(qq422016 qtio422016.Writer, domains []*pdl.Domain) {
//line extra.qtpl:414
	qw422016 := qt422016.AcquireWriter(qq422016)
//line extra.qtpl:414
	StreamExtraMessageTemplate(qw422016, domains)
//line extra.qtpl:414
	qt422016.ReleaseWriter(qw422016)
//line extra.qtpl:414
}

//line extra.qtpl:414
func ExtraMessageTemplate(domains []*pdl.Domain) string {
//line extra.qtpl:414
	qb422016 := qt422016.AcquireByteBuffer()
//line extra.qtpl:414
	WriteExtraMessageTemplate(qb422016, domains)
//line extra.qtpl:414
	qs422016 := string(qb422016.B)
//line extra.qtpl:414
	qt422016.ReleaseByteBuffer(qb422016)
//line extra.qtpl:414
	return qs422016
//line extra.qtpl:414
}
