// Code generated by qtc from "file.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line file.qtpl:1
package cdprototpl

//line file.qtpl:1
import (
	"sort"

	"github.com/chromedp/pdlgen/util/pdl"
)

// FileHeader is the file header template.

//line file.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line file.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line file.qtpl:8
func StreamFileHeader(qw422016 *qt422016.Writer, pkgName string, d *pdl.Domain) {
//line file.qtpl:8
	qw422016.N().S(`
`)
//line file.qtpl:9
	if d != nil {
//line file.qtpl:9
		qw422016.N().S(`// Package `)
//line file.qtpl:9
		qw422016.N().S(PackageName(d))
//line file.qtpl:9
		qw422016.N().S(` provides the Chrome DevTools Protocol
// commands, types, and events for the `)
//line file.qtpl:10
		qw422016.N().S(d.Domain.String())
//line file.qtpl:10
		qw422016.N().S(` domain.
// `)
//line file.qtpl:11
		if desc := d.Description; desc != "" {
//line file.qtpl:11
			qw422016.N().S(`
`)
//line file.qtpl:12
			qw422016.N().S(FormatComment(desc, "", ""))
//line file.qtpl:12
			qw422016.N().S(`
//`)
//line file.qtpl:13
		}
//line file.qtpl:13
		qw422016.N().S(`
// Generated by the pdlgen command.`)
//line file.qtpl:14
	}
//line file.qtpl:14
	qw422016.N().S(`
package `)
//line file.qtpl:15
	qw422016.N().S(pkgName)
//line file.qtpl:15
	qw422016.N().S(`

`)
//line file.qtpl:17
	qw422016.N().S("// Code generated by pdlgen. DO NOT EDIT.")
//line file.qtpl:17
	qw422016.N().S(`
`)
//line file.qtpl:18
}

//line file.qtpl:18
func WriteFileHeader(qq422016 qtio422016.Writer, pkgName string, d *pdl.Domain) {
//line file.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line file.qtpl:18
	StreamFileHeader(qw422016, pkgName, d)
//line file.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line file.qtpl:18
}

//line file.qtpl:18
func FileHeader(pkgName string, d *pdl.Domain) string {
//line file.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line file.qtpl:18
	WriteFileHeader(qb422016, pkgName, d)
//line file.qtpl:18
	qs422016 := string(qb422016.B)
//line file.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line file.qtpl:18
	return qs422016
//line file.qtpl:18
}

// FileImportTemplate is a general import template.

//line file.qtpl:21
func StreamFileImportTemplate(qw422016 *qt422016.Writer, importMap map[string]string) {
//line file.qtpl:22
	var keys []string
	for k, _ := range importMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

//line file.qtpl:27
	qw422016.N().S(`
import (`)
//line file.qtpl:28
	for _, k := range keys {
//line file.qtpl:29
		v := importMap[k]

//line file.qtpl:30
		qw422016.N().S(`
	`)
//line file.qtpl:31
		if k != v {
//line file.qtpl:31
			qw422016.N().S(v)
//line file.qtpl:31
			qw422016.N().S(` `)
//line file.qtpl:31
		}
//line file.qtpl:31
		qw422016.N().Q(k)
//line file.qtpl:31
	}
//line file.qtpl:31
	qw422016.N().S(`
)
`)
//line file.qtpl:33
}

//line file.qtpl:33
func WriteFileImportTemplate(qq422016 qtio422016.Writer, importMap map[string]string) {
//line file.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line file.qtpl:33
	StreamFileImportTemplate(qw422016, importMap)
//line file.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line file.qtpl:33
}

//line file.qtpl:33
func FileImportTemplate(importMap map[string]string) string {
//line file.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line file.qtpl:33
	WriteFileImportTemplate(qb422016, importMap)
//line file.qtpl:33
	qs422016 := string(qb422016.B)
//line file.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line file.qtpl:33
	return qs422016
//line file.qtpl:33
}
