// Code generated by qtc from "type.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line type.qtpl:1
package cdprototpl

//line type.qtpl:1
import (
	"strconv"
	"strings"

	"github.com/chromedp/pdlgen/util/pdl"
)

// TypeTemplate is a template for a pdl type.

//line type.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line type.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line type.qtpl:9
func StreamTypeTemplate(qw422016 *qt422016.Writer, t *pdl.Type, prefix, suffix string, d *pdl.Domain, domains []*pdl.Domain, v interface{}, noExposeOverride, omitOnlyWhenOptional bool) {
//line type.qtpl:10
	typ := prefix + CamelName(t) + suffix

	var extra []*pdl.Type
	switch x := v.(type) {
	case []*pdl.Type:
		extra = x
	}

	docRefLink := DocRefLink(t)

//line type.qtpl:19
	qw422016.N().S(`
`)
//line type.qtpl:20
	qw422016.N().S(FormatComment(t.Description, "", typ+" "))
//line type.qtpl:20
	if t.RawType != "command" && t.RawType != "returns" && docRefLink != "" {
//line type.qtpl:20
		qw422016.N().S(`
//
// See: `)
//line type.qtpl:22
		qw422016.N().S(docRefLink)
//line type.qtpl:22
	}
//line type.qtpl:22
	qw422016.N().S(`
type `)
//line type.qtpl:23
	qw422016.N().S(typ)
//line type.qtpl:23
	qw422016.N().S(` `)
//line type.qtpl:23
	qw422016.N().S(GoTypeDef(t, d, domains, extra, noExposeOverride, omitOnlyWhenOptional))
//line type.qtpl:23
	qw422016.N().S(`
`)
//line type.qtpl:24
	if t.Parameters == nil && t.Type != pdl.TypeArray && t.Type != pdl.TypeObject && t.Type != pdl.TypeAny {
//line type.qtpl:25
		gz := GoEnumType(t.Type)
		z := gz
		if strings.Contains(z, ".") {
			z = z[strings.Index(z, ".")+1:]
		}
		z = strings.ToUpper(z[:1]) + z[1:]

//line type.qtpl:31
		qw422016.N().S(`
// `)
//line type.qtpl:32
		qw422016.N().S(z)
//line type.qtpl:32
		qw422016.N().S(` returns the `)
//line type.qtpl:32
		qw422016.N().S(typ)
//line type.qtpl:32
		qw422016.N().S(` as `)
//line type.qtpl:32
		qw422016.N().S(gz)
//line type.qtpl:32
		qw422016.N().S(` value.
func (t `)
//line type.qtpl:33
		qw422016.N().S(typ)
//line type.qtpl:33
		qw422016.N().S(`) `)
//line type.qtpl:33
		qw422016.N().S(z)
//line type.qtpl:33
		qw422016.N().S(`() `)
//line type.qtpl:33
		qw422016.N().S(gz)
//line type.qtpl:33
		qw422016.N().S(` {
	return `)
//line type.qtpl:34
		qw422016.N().S(gz)
//line type.qtpl:34
		qw422016.N().S(`(t)
}
`)
//line type.qtpl:36
	}
//line type.qtpl:36
	qw422016.N().S(`
`)
//line type.qtpl:37
	if ev := t.Enum; ev != nil {
//line type.qtpl:38
		gz := GoEnumType(t.Type)
		z := gz
		if strings.Contains(z, ".") {
			z = z[strings.Index(z, ".")+1:]
		}
		z = strings.ToUpper(z[:1]) + z[1:]

//line type.qtpl:44
		qw422016.N().S(`// `)
//line type.qtpl:44
		qw422016.N().S(typ)
//line type.qtpl:44
		qw422016.N().S(` values.
const (`)
//line type.qtpl:45
		for i, e := range ev {
//line type.qtpl:46
			n := EnumValueName(t, e)
			val := `"` + e + `"`
			if t.Type == pdl.TypeInteger && t.EnumBitMask {
				val = strconv.Itoa(1 << uint(i-1))
			} else if t.Type == pdl.TypeInteger {
				val = strconv.Itoa(i + 1)
			}

//line type.qtpl:53
			qw422016.N().S(`
	`)
//line type.qtpl:54
			qw422016.N().S(n)
//line type.qtpl:54
			qw422016.N().S(` `)
//line type.qtpl:54
			qw422016.N().S(typ)
//line type.qtpl:54
			qw422016.N().S(` = `)
//line type.qtpl:54
			qw422016.N().S(val)
//line type.qtpl:54
		}
//line type.qtpl:54
		qw422016.N().S(`
)
`)
//line type.qtpl:56
		if t.Type != pdl.TypeString {
//line type.qtpl:56
			qw422016.N().S(`
// String returns the `)
//line type.qtpl:57
			qw422016.N().S(typ)
//line type.qtpl:57
			qw422016.N().S(` as string value.
func (t `)
//line type.qtpl:58
			qw422016.N().S(typ)
//line type.qtpl:58
			qw422016.N().S(`) String() string {
	switch t {`)
//line type.qtpl:59
			for _, e := range t.Enum {
//line type.qtpl:59
				qw422016.N().S(`
	case `)
//line type.qtpl:60
				qw422016.N().S(EnumValueName(t, e))
//line type.qtpl:60
				qw422016.N().S(`:
		return `)
//line type.qtpl:61
				qw422016.N().Q(e)
//line type.qtpl:61
			}
//line type.qtpl:61
			qw422016.N().S(`
	}

	return fmt.Sprintf("`)
//line type.qtpl:64
			qw422016.N().S(typ)
//line type.qtpl:64
			qw422016.N().S(`(%d)", t)
}
`)
//line type.qtpl:66
		}
//line type.qtpl:66
		qw422016.N().S(`

// MarshalEasyJSON satisfies easyjson.Marshaler.
func (t `)
//line type.qtpl:69
		qw422016.N().S(typ)
//line type.qtpl:69
		qw422016.N().S(`) MarshalEasyJSON(out *jwriter.Writer) {
	out.`)
//line type.qtpl:70
		qw422016.N().S(z)
//line type.qtpl:70
		qw422016.N().S(`(`)
//line type.qtpl:70
		qw422016.N().S(gz)
//line type.qtpl:70
		qw422016.N().S(`(t))
}

// MarshalJSON satisfies json.Marshaler.
func (t `)
//line type.qtpl:74
		qw422016.N().S(typ)
//line type.qtpl:74
		qw422016.N().S(`) MarshalJSON() ([]byte, error) {
	return easyjson.Marshal(t)
}

// UnmarshalEasyJSON satisfies easyjson.Unmarshaler.
func (t *`)
//line type.qtpl:79
		qw422016.N().S(typ)
//line type.qtpl:79
		qw422016.N().S(`) UnmarshalEasyJSON(in *jlexer.Lexer) {
	switch `)
//line type.qtpl:80
		qw422016.N().S(typ)
//line type.qtpl:80
		qw422016.N().S(`(in.`)
//line type.qtpl:80
		qw422016.N().S(z)
//line type.qtpl:80
		qw422016.N().S(`()) {`)
//line type.qtpl:80
		for _, e := range t.Enum {
//line type.qtpl:81
			n := EnumValueName(t, e)

//line type.qtpl:82
			qw422016.N().S(`
	case `)
//line type.qtpl:83
			qw422016.N().S(n)
//line type.qtpl:83
			qw422016.N().S(`:
		*t = `)
//line type.qtpl:84
			qw422016.N().S(n)
//line type.qtpl:84
		}
//line type.qtpl:84
		qw422016.N().S(`

	default:
		in.AddError(errors.New("unknown `)
//line type.qtpl:87
		qw422016.N().S(typ)
//line type.qtpl:87
		qw422016.N().S(` value"))
	}
}

// UnmarshalJSON satisfies json.Unmarshaler.
func (t *`)
//line type.qtpl:92
		qw422016.N().S(typ)
//line type.qtpl:92
		qw422016.N().S(`) UnmarshalJSON(buf []byte) error {
	return easyjson.Unmarshal(buf, t)
}`)
//line type.qtpl:94
	}
//line type.qtpl:94
	qw422016.N().S(`
`)
//line type.qtpl:95
	if t.Extra != "" {
//line type.qtpl:95
		qw422016.N().S(`
`)
//line type.qtpl:96
		qw422016.N().S(t.Extra)
//line type.qtpl:96
	}
//line type.qtpl:96
	qw422016.N().S(`
`)
//line type.qtpl:97
}

//line type.qtpl:97
func WriteTypeTemplate(qq422016 qtio422016.Writer, t *pdl.Type, prefix, suffix string, d *pdl.Domain, domains []*pdl.Domain, v interface{}, noExposeOverride, omitOnlyWhenOptional bool) {
//line type.qtpl:97
	qw422016 := qt422016.AcquireWriter(qq422016)
//line type.qtpl:97
	StreamTypeTemplate(qw422016, t, prefix, suffix, d, domains, v, noExposeOverride, omitOnlyWhenOptional)
//line type.qtpl:97
	qt422016.ReleaseWriter(qw422016)
//line type.qtpl:97
}

//line type.qtpl:97
func TypeTemplate(t *pdl.Type, prefix, suffix string, d *pdl.Domain, domains []*pdl.Domain, v interface{}, noExposeOverride, omitOnlyWhenOptional bool) string {
//line type.qtpl:97
	qb422016 := qt422016.AcquireByteBuffer()
//line type.qtpl:97
	WriteTypeTemplate(qb422016, t, prefix, suffix, d, domains, v, noExposeOverride, omitOnlyWhenOptional)
//line type.qtpl:97
	qs422016 := string(qb422016.B)
//line type.qtpl:97
	qt422016.ReleaseByteBuffer(qb422016)
//line type.qtpl:97
	return qs422016
//line type.qtpl:97
}
